# Makefile for a program with multiple .cpp files
#  -- from _C++ for Lazy Programmers_, but I claim no copyright

PROG	= myprogram			#What program am I building?
SRCS	= $(wildcard *.cpp)	#What .cpp files do I have?
OBJS	= ${SRCS:.cpp=.o}	#What .o   files do I build?

$(PROG): $(OBJS)		# Build the program
		g++ -o $@ -g $^

clean:					# Clean up files
		rm -f $(PROG)
		rm -f *.o

%.o: 	%.cpp			# Make the .o files
		g++ -g -o $@ -c $<
